# Software Engineering II
# Dr.Salamah
# Team 6 - Byte Me

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel)
import EditHookCollectionOverlay
import EditHook
import HookCollectionExcecutionError
import HookExcecutionError
import ProxyBehaviorDisabledNotification
import ProxyBehaviorEnabledNotification
import QueueError
import SavedFuzzed

class Ui_MainWindow():

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1118, 870)
        MainWindow.setStyleSheet("")
        self.MainWidget = QtWidgets.QWidget(MainWindow)
        self.MainWidget.setObjectName("MainWidget")
        self.ContentViewWidget = QtWidgets.QStackedWidget(self.MainWidget)
        self.ContentViewWidget.setGeometry(QtCore.QRect(270, 10, 841, 851))
        self.ContentViewWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.ContentViewWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ContentViewWidget.setLineWidth(1)
        self.ContentViewWidget.setMidLineWidth(0)
        self.ContentViewWidget.setObjectName("ContentViewWidget")
        self.HookCollectionViewPage = QtWidgets.QWidget()
        self.HookCollectionViewPage.setObjectName("HookCollectionViewPage")
        self.HookCollectionLabel = QtWidgets.QLabel(self.HookCollectionViewPage)
        self.HookCollectionLabel.setGeometry(QtCore.QRect(0, 0, 841, 51))
        self.HookCollectionLabel.setStyleSheet("border-style: solid solid none solid;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgb(111, 168, 220), stop:1 rgb(159, 197, 232));")
        self.HookCollectionLabel.setObjectName("HookCollectionLabel")
        self.HCVAddHookButton = QtWidgets.QPushButton(self.HookCollectionViewPage)
        self.HCVAddHookButton.setGeometry(QtCore.QRect(20, 70, 151, 31))
        self.HCVAddHookButton.setStyleSheet("background-color: rgb(244, 244, 244);\n"
"box-shadow:    3px 3px rgb(239, 239, 239);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.HCVAddHookButton.setCheckable(False)
        self.HCVAddHookButton.setChecked(False)
        self.HCVAddHookButton.setFlat(False)
        self.HCVAddHookButton.setObjectName("HCVAddHookButton")
        self.HCVSearchBox = QtWidgets.QLineEdit(self.HookCollectionViewPage)
        self.HCVSearchBox.setGeometry(QtCore.QRect(580, 69, 241, 31))
        self.HCVSearchBox.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.HCVSearchBox.setClearButtonEnabled(False)
        self.HCVSearchBox.setObjectName("HCVSearchBox")
        self.HCVDeleteHookButton = QtWidgets.QPushButton(self.HookCollectionViewPage)
        self.HCVDeleteHookButton.setGeometry(QtCore.QRect(260, 70, 71, 31))
        self.HCVDeleteHookButton.setStyleSheet("background-color: rgb(244, 244, 244);\n"
"box-shadow:    3px 3px rgb(239, 239, 239);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.HCVDeleteHookButton.setCheckable(False)
        self.HCVDeleteHookButton.setChecked(False)
        self.HCVDeleteHookButton.setFlat(False)
        self.HCVDeleteHookButton.setObjectName("HCVDeleteHookButton")
        self.HCVEditHookButton = QtWidgets.QPushButton(self.HookCollectionViewPage)
        self.HCVEditHookButton.setGeometry(QtCore.QRect(180, 70, 71, 31))
        self.HCVEditHookButton.setStyleSheet("background-color: rgb(244, 244, 244);\n"
"box-shadow:    3px 3px rgb(239, 239, 239);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.HCVEditHookButton.setCheckable(False)
        self.HCVEditHookButton.setChecked(False)
        self.HCVEditHookButton.setFlat(False)
        self.HCVEditHookButton.setObjectName("HCVEditHookButton")


        self.HCVSearchLable = QtWidgets.QLabel(self.HookCollectionViewPage)
        self.HCVSearchLable.setGeometry(QtCore.QRect(490, 80, 71, 21))
        self.HCVSearchLable.setStyleSheet("background-color: rgb(255, 255, 255, 0);")
        self.HCVSearchLable.setObjectName("HCVSearchLable")
        self.HVHookPropertiesWidget_2 = QtWidgets.QWidget(self.HookCollectionViewPage)
        self.HVHookPropertiesWidget_2.setGeometry(QtCore.QRect(20, 120, 801, 711))
        self.HVHookPropertiesWidget_2.setObjectName("HVHookPropertiesWidget_2")
        self.HookCollectionPropertiesLable = QtWidgets.QLabel(self.HVHookPropertiesWidget_2)
        self.HookCollectionPropertiesLable.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.HookCollectionPropertiesLable.setStyleSheet("border-style: solid solid none solid;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgb(111, 168, 220), stop:1 rgb(159, 197, 232));")
        self.HookCollectionPropertiesLable.setObjectName("HookCollectionPropertiesLable")
        self.ContentViewWidget.addWidget(self.HookCollectionViewPage)
        self.HookViewPage = QtWidgets.QWidget()
        self.HookViewPage.setObjectName("HookViewPage")
        self.HookViewLable = QtWidgets.QLabel(self.HookViewPage)
        self.HookViewLable.setGeometry(QtCore.QRect(0, 0, 841, 51))
        self.HookViewLable.setStyleSheet("border-style: solid solid none solid;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgb(111, 168, 220), stop:1 rgb(159, 197, 232));")
        self.HookViewLable.setObjectName("HookViewLable")
        self.HVAddHookButton = QtWidgets.QPushButton(self.HookViewPage)
        self.HVAddHookButton.setGeometry(QtCore.QRect(20, 70, 71, 31))
        self.HVAddHookButton.setStyleSheet("background-color: rgb(244, 244, 244);\n"
"box-shadow:    3px 3px rgb(239, 239, 239);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.HVAddHookButton.setCheckable(False)
        self.HVAddHookButton.setChecked(False)
        self.HVAddHookButton.setFlat(False)
        self.HVAddHookButton.setObjectName("HVAddHookButton")
        self.HVEditHookButton = QtWidgets.QPushButton(self.HookViewPage)
        self.HVEditHookButton.setGeometry(QtCore.QRect(100, 70, 71, 31))
        self.HVEditHookButton.setStyleSheet("background-color: rgb(244, 244, 244);\n"
"box-shadow:    3px 3px rgb(239, 239, 239);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.HVEditHookButton.setCheckable(False)
        self.HVEditHookButton.setChecked(False)
        self.HVEditHookButton.setFlat(False)
        self.HVEditHookButton.setObjectName("HVEditHookButton")
        self.HVDeleteHookButton = QtWidgets.QPushButton(self.HookViewPage)
        self.HVDeleteHookButton.setGeometry(QtCore.QRect(180, 70, 71, 31))
        self.HVDeleteHookButton.setStyleSheet("background-color: rgb(244, 244, 244);\n"
"box-shadow:    3px 3px rgb(239, 239, 239);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.HVDeleteHookButton.setCheckable(False)
        self.HVDeleteHookButton.setChecked(False)
        self.HVDeleteHookButton.setFlat(False)
        self.HVDeleteHookButton.setObjectName("HVDeleteHookButton")
        self.HVSearchLable = QtWidgets.QLabel(self.HookViewPage)
        self.HVSearchLable.setGeometry(QtCore.QRect(490, 80, 71, 21))
        self.HVSearchLable.setStyleSheet("background-color: rgb(255, 255, 255, 0);")
        self.HVSearchLable.setObjectName("HVSearchLable")
        self.HVSearchBox = QtWidgets.QLineEdit(self.HookViewPage)
        self.HVSearchBox.setGeometry(QtCore.QRect(580, 69, 241, 31))
        self.HVSearchBox.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.HVSearchBox.setClearButtonEnabled(False)
        self.HVSearchBox.setObjectName("HVSearchBox")
        self.HVHookPropertiesFrame = QtWidgets.QFrame(self.HookViewPage)
        self.HVHookPropertiesFrame.setGeometry(QtCore.QRect(20, 120, 801, 711))
        self.HVHookPropertiesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HVHookPropertiesFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.HVHookPropertiesFrame.setLineWidth(1)
        self.HVHookPropertiesFrame.setObjectName("HVHookPropertiesFrame")
        self.HookPropertiesLable = QtWidgets.QLabel(self.HVHookPropertiesFrame)
        self.HookPropertiesLable.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.HookPropertiesLable.setStyleSheet("border-style: solid solid none solid;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgb(111, 168, 220), stop:1 rgb(159, 197, 232));")
        self.HookPropertiesLable.setObjectName("HookPropertiesLable")
        self.tableWidget = QtWidgets.QTableWidget(self.HVHookPropertiesFrame)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 781, 121))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 3, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.ContentViewWidget.addWidget(self.HookViewPage)
        self.LivePacketViewPage = QtWidgets.QWidget()
        self.LivePacketViewPage.setObjectName("LivePacketViewPage")
        self.LivePacketViewLable = QtWidgets.QLabel(self.LivePacketViewPage)
        self.LivePacketViewLable.setGeometry(QtCore.QRect(0, 0, 841, 51))
        self.LivePacketViewLable.setStyleSheet("border-style: solid solid none solid;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgb(111, 168, 220), stop:1 rgb(159, 197, 232));")
        self.LivePacketViewLable.setObjectName("LivePacketViewLable")
        self.ProxyBox = QtWidgets.QComboBox(self.LivePacketViewPage)
        self.ProxyBox.setGeometry(QtCore.QRect(140, 60, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ProxyBox.setFont(font)
        self.ProxyBox.setFrame(True)
        self.ProxyBox.setObjectName("ProxyBox")
        self.ProxyBox.addItem("")
        self.ProxyBox.addItem("")
        self.ProxyBehaviorLabel = QtWidgets.QLabel(self.LivePacketViewPage)
        self.ProxyBehaviorLabel.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.ProxyBehaviorLabel.setObjectName("ProxyBehaviorLabel")
        self.IntercepBehaviorLabel = QtWidgets.QLabel(self.LivePacketViewPage)
        self.IntercepBehaviorLabel.setGeometry(QtCore.QRect(260, 60, 171, 16))
        self.IntercepBehaviorLabel.setObjectName("IntercepBehaviorLabel")
        self.InterceptBox = QtWidgets.QComboBox(self.LivePacketViewPage)
        self.InterceptBox.setGeometry(QtCore.QRect(440, 60, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.InterceptBox.setFont(font)
        self.InterceptBox.setFrame(True)
        self.InterceptBox.setObjectName("InterceptBox")
        self.InterceptBox.addItem("")
        self.InterceptBox.addItem("")
        self.QueueSizeLabel = QtWidgets.QLabel(self.LivePacketViewPage)
        self.QueueSizeLabel.setGeometry(QtCore.QRect(620, 60, 91, 16))
        self.QueueSizeLabel.setObjectName("QueueSizeLabel")
        self.QueueSizeEdit = QtWidgets.QLineEdit(self.LivePacketViewPage)
        self.QueueSizeEdit.setGeometry(QtCore.QRect(720, 60, 113, 20))
        self.QueueSizeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.QueueSizeEdit.setObjectName("QueueSizeEdit")
        self.FilterFrame = QtWidgets.QFrame(self.LivePacketViewPage)
        self.FilterFrame.setGeometry(QtCore.QRect(10, 90, 821, 80))
        self.FilterFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.FilterFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FilterFrame.setObjectName("FilterFrame")
        self.CaptureFiltreLabel = QtWidgets.QLabel(self.FilterFrame)
        self.CaptureFiltreLabel.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.CaptureFiltreLabel.setObjectName("CaptureFiltreLabel")
        self.FilterLable = QtWidgets.QLabel(self.FilterFrame)
        self.FilterLable.setGeometry(QtCore.QRect(20, 40, 54, 14))
        self.FilterLable.setObjectName("FilterLable")
        self.FilterExpressionEdit = QtWidgets.QLineEdit(self.FilterFrame)
        self.FilterExpressionEdit.setGeometry(QtCore.QRect(80, 40, 571, 21))
        self.FilterExpressionEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterExpressionEdit.setObjectName("FilterExpressionEdit")
        self.ApplyExpressionButton = QtWidgets.QPushButton(self.FilterFrame)
        self.ApplyExpressionButton.setGeometry(QtCore.QRect(660, 40, 71, 25))
        self.ApplyExpressionButton.setObjectName("ApplyExpressionButton")
        self.ClearExpressionButton = QtWidgets.QPushButton(self.FilterFrame)
        self.ClearExpressionButton.setGeometry(QtCore.QRect(740, 40, 71, 25))
        self.ClearExpressionButton.setObjectName("ClearExpressionButton")
        self.PacketAreaFrame = QtWidgets.QFrame(self.LivePacketViewPage)
        self.PacketAreaFrame.setGeometry(QtCore.QRect(10, 180, 821, 351))
        self.PacketAreaFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.PacketAreaFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.PacketAreaFrame.setObjectName("PacketAreaFrame")
        self.PacketAreaLabel = QtWidgets.QLabel(self.PacketAreaFrame)
        self.PacketAreaLabel.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.PacketAreaLabel.setObjectName("PacketAreaLabel")
        self.PacketAreaTabs = QtWidgets.QTabWidget(self.PacketAreaFrame)
        self.PacketAreaTabs.setGeometry(QtCore.QRect(10, 40, 721, 301))
        self.PacketAreaTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.PacketAreaTabs.setObjectName("PacketAreaTabs")
        self.DissectedTab = QtWidgets.QWidget()
        self.DissectedTab.setObjectName("DissectedTab")
        self.PacketAreaTabs.addTab(self.DissectedTab, "")
        self.BinaryTab = QtWidgets.QWidget()
        self.BinaryTab.setObjectName("BinaryTab")
        self.PacketAreaTabs.addTab(self.BinaryTab, "")
        self.HexTab = QtWidgets.QWidget()
        self.HexTab.setObjectName("HexTab")
        self.PacketAreaTabs.addTab(self.HexTab, "")
        self.PacketAreaClearButton = QtWidgets.QPushButton(self.PacketAreaFrame)
        self.PacketAreaClearButton.setGeometry(QtCore.QRect(740, 310, 71, 25))
        self.PacketAreaClearButton.setObjectName("PacketAreaClearButton")
        self.FieldAreaFrame = QtWidgets.QFrame(self.LivePacketViewPage)
        self.FieldAreaFrame.setGeometry(QtCore.QRect(10, 540, 451, 301))
        self.FieldAreaFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.FieldAreaFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FieldAreaFrame.setObjectName("FieldAreaFrame")
        self.FieldAreaLabel = QtWidgets.QLabel(self.FieldAreaFrame)
        self.FieldAreaLabel.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.FieldAreaLabel.setObjectName("FieldAreaLabel")
        self.FieldAreaTable = QtWidgets.QTableWidget(self.FieldAreaFrame)
        self.FieldAreaTable.setGeometry(QtCore.QRect(10, 40, 431, 211))
        self.FieldAreaTable.setShowGrid(False)
        self.FieldAreaTable.setObjectName("FieldAreaTable")
        self.FieldAreaTable.setColumnCount(4)
        self.FieldAreaTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.FieldAreaTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.FieldAreaTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.FieldAreaTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.FieldAreaTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.FieldAreaTable.setHorizontalHeaderItem(3, item)
        self.FieldAreaTable.horizontalHeader().setStretchLastSection(True)
        self.FieldAreaTable.verticalHeader().setVisible(False)
        self.FieldAreaTable.verticalHeader().setStretchLastSection(False)
        self.FASaveButton = QtWidgets.QPushButton(self.FieldAreaFrame)
        self.FASaveButton.setGeometry(QtCore.QRect(170, 270, 111, 25))
        self.FASaveButton.setObjectName("FASaveButton")
        self.FAForwardButton = QtWidgets.QPushButton(self.FieldAreaFrame)
        self.FAForwardButton.setGeometry(QtCore.QRect(290, 270, 71, 25))
        self.FAForwardButton.setObjectName("FAForwardButton")
        self.FADropButton = QtWidgets.QPushButton(self.FieldAreaFrame)
        self.FADropButton.setGeometry(QtCore.QRect(370, 270, 71, 25))
        self.FADropButton.setObjectName("FADropButton")
        self.FuzzingAreaFrame = QtWidgets.QFrame(self.LivePacketViewPage)
        self.FuzzingAreaFrame.setGeometry(QtCore.QRect(500, 540, 331, 301))
        self.FuzzingAreaFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.FuzzingAreaFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FuzzingAreaFrame.setObjectName("FuzzingAreaFrame")
        self.FuzzingAreaLabel = QtWidgets.QLabel(self.FuzzingAreaFrame)
        self.FuzzingAreaLabel.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.FuzzingAreaLabel.setObjectName("FuzzingAreaLabel")
        self.FAPacketNameLabel = QtWidgets.QLabel(self.FuzzingAreaFrame)
        self.FAPacketNameLabel.setGeometry(QtCore.QRect(10, 40, 141, 20))
        self.FAPacketNameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.FAPacketNameLabel.setWordWrap(False)
        self.FAPacketNameLabel.setObjectName("FAPacketNameLabel")
        self.FAPacketNameEdit = QtWidgets.QLineEdit(self.FuzzingAreaFrame)
        self.FAPacketNameEdit.setGeometry(QtCore.QRect(150, 40, 171, 20))
        self.FAPacketNameEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.FAPacketNameEdit.setObjectName("FAPacketNameEdit")
        self.FAFieldNameLabel = QtWidgets.QLabel(self.FuzzingAreaFrame)
        self.FAFieldNameLabel.setGeometry(QtCore.QRect(10, 80, 121, 20))
        self.FAFieldNameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.FAFieldNameLabel.setWordWrap(False)
        self.FAFieldNameLabel.setObjectName("FAFieldNameLabel")
        self.FAFieldNameEdit = QtWidgets.QLineEdit(self.FuzzingAreaFrame)
        self.FAFieldNameEdit.setGeometry(QtCore.QRect(150, 80, 171, 20))
        self.FAFieldNameEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.FAFieldNameEdit.setObjectName("FAFieldNameEdit")
        self.FAReturnTypeLabel = QtWidgets.QLabel(self.FuzzingAreaFrame)
        self.FAReturnTypeLabel.setGeometry(QtCore.QRect(10, 120, 141, 20))
        self.FAReturnTypeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.FAReturnTypeLabel.setWordWrap(False)
        self.FAReturnTypeLabel.setObjectName("FAReturnTypeLabel")
        self.FAReturnTypeEdit = QtWidgets.QLineEdit(self.FuzzingAreaFrame)
        self.FAReturnTypeEdit.setGeometry(QtCore.QRect(150, 120, 171, 20))
        self.FAReturnTypeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.FAReturnTypeEdit.setObjectName("FAReturnTypeEdit")
        self.FAMinimumLabel = QtWidgets.QLabel(self.FuzzingAreaFrame)
        self.FAMinimumLabel.setGeometry(QtCore.QRect(80, 160, 61, 20))
        self.FAMinimumLabel.setTextFormat(QtCore.Qt.AutoText)
        self.FAMinimumLabel.setWordWrap(False)
        self.FAMinimumLabel.setObjectName("FAMinimumLabel")
        self.FAMinimumEdit = QtWidgets.QLineEdit(self.FuzzingAreaFrame)
        self.FAMinimumEdit.setGeometry(QtCore.QRect(150, 160, 171, 20))
        self.FAMinimumEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.FAMinimumEdit.setObjectName("FAMinimumEdit")
        self.FAMaximumLabel = QtWidgets.QLabel(self.FuzzingAreaFrame)
        self.FAMaximumLabel.setGeometry(QtCore.QRect(80, 200, 61, 20))
        self.FAMaximumLabel.setTextFormat(QtCore.Qt.AutoText)
        self.FAMaximumLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.FAMaximumLabel.setWordWrap(False)
        self.FAMaximumLabel.setObjectName("FAMaximumLabel")
        self.FAMaximumEdit = QtWidgets.QLineEdit(self.FuzzingAreaFrame)
        self.FAMaximumEdit.setGeometry(QtCore.QRect(150, 200, 171, 20))
        self.FAMaximumEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.FAMaximumEdit.setObjectName("FAMaximumEdit")
        self.FAStopButton = QtWidgets.QPushButton(self.FuzzingAreaFrame)
        self.FAStopButton.setGeometry(QtCore.QRect(250, 270, 71, 25))
        self.FAStopButton.setObjectName("FAStopButton")
        self.FAFuzzButton = QtWidgets.QPushButton(self.FuzzingAreaFrame)
        self.FAFuzzButton.setGeometry(QtCore.QRect(170, 270, 71, 25))
        self.FAFuzzButton.setObjectName("FAFuzzButton")
        self.FAAddButton = QtWidgets.QToolButton(self.LivePacketViewPage)
        self.FAAddButton.setGeometry(QtCore.QRect(470, 640, 27, 20))
        self.FAAddButton.setArrowType(QtCore.Qt.RightArrow)
        self.FAAddButton.setObjectName("FAAddButton")
        self.FASubstractButton = QtWidgets.QToolButton(self.LivePacketViewPage)
        self.FASubstractButton.setGeometry(QtCore.QRect(470, 690, 27, 20))
        self.FASubstractButton.setArrowType(QtCore.Qt.LeftArrow)
        self.FASubstractButton.setObjectName("FASubstractButton")
        self.ContentViewWidget.addWidget(self.LivePacketViewPage)
        self.PCAPViewPage = QtWidgets.QWidget()
        self.PCAPViewPage.setObjectName("PCAPViewPage")
        self.FuzzingAreaFrame_2 = QtWidgets.QFrame(self.PCAPViewPage)
        self.FuzzingAreaFrame_2.setGeometry(QtCore.QRect(500, 540, 331, 301))
        self.FuzzingAreaFrame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.FuzzingAreaFrame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FuzzingAreaFrame_2.setObjectName("FuzzingAreaFrame_2")
        self.FuzzingAreaLabel_2 = QtWidgets.QLabel(self.FuzzingAreaFrame_2)
        self.FuzzingAreaLabel_2.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.FuzzingAreaLabel_2.setObjectName("FuzzingAreaLabel_2")
        self.FAPacketNameLabel_2 = QtWidgets.QLabel(self.FuzzingAreaFrame_2)
        self.FAPacketNameLabel_2.setGeometry(QtCore.QRect(10, 40, 141, 20))
        self.FAPacketNameLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.FAPacketNameLabel_2.setWordWrap(False)
        self.FAPacketNameLabel_2.setObjectName("FAPacketNameLabel_2")
        self.FAPacketNameEdit_2 = QtWidgets.QLineEdit(self.FuzzingAreaFrame_2)
        self.FAPacketNameEdit_2.setGeometry(QtCore.QRect(150, 40, 171, 20))
        self.FAPacketNameEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.FAPacketNameEdit_2.setObjectName("FAPacketNameEdit_2")
        self.FAFieldNameLabel_2 = QtWidgets.QLabel(self.FuzzingAreaFrame_2)
        self.FAFieldNameLabel_2.setGeometry(QtCore.QRect(10, 80, 121, 20))
        self.FAFieldNameLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.FAFieldNameLabel_2.setWordWrap(False)
        self.FAFieldNameLabel_2.setObjectName("FAFieldNameLabel_2")
        self.FAFieldNameEdit_2 = QtWidgets.QLineEdit(self.FuzzingAreaFrame_2)
        self.FAFieldNameEdit_2.setGeometry(QtCore.QRect(150, 80, 171, 20))
        self.FAFieldNameEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.FAFieldNameEdit_2.setObjectName("FAFieldNameEdit_2")
        self.FAReturnTypeLabel_2 = QtWidgets.QLabel(self.FuzzingAreaFrame_2)
        self.FAReturnTypeLabel_2.setGeometry(QtCore.QRect(10, 120, 141, 20))
        self.FAReturnTypeLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.FAReturnTypeLabel_2.setWordWrap(False)
        self.FAReturnTypeLabel_2.setObjectName("FAReturnTypeLabel_2")
        self.FAReturnTypeEdit_2 = QtWidgets.QLineEdit(self.FuzzingAreaFrame_2)
        self.FAReturnTypeEdit_2.setGeometry(QtCore.QRect(150, 120, 171, 20))
        self.FAReturnTypeEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.FAReturnTypeEdit_2.setObjectName("FAReturnTypeEdit_2")
        self.FAMinimumLabel_2 = QtWidgets.QLabel(self.FuzzingAreaFrame_2)
        self.FAMinimumLabel_2.setGeometry(QtCore.QRect(80, 160, 61, 20))
        self.FAMinimumLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.FAMinimumLabel_2.setWordWrap(False)
        self.FAMinimumLabel_2.setObjectName("FAMinimumLabel_2")
        self.FAMinimumEdit_2 = QtWidgets.QLineEdit(self.FuzzingAreaFrame_2)
        self.FAMinimumEdit_2.setGeometry(QtCore.QRect(150, 160, 171, 20))
        self.FAMinimumEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.FAMinimumEdit_2.setObjectName("FAMinimumEdit_2")
        self.FAMaximumLabel_2 = QtWidgets.QLabel(self.FuzzingAreaFrame_2)
        self.FAMaximumLabel_2.setGeometry(QtCore.QRect(80, 200, 61, 20))
        self.FAMaximumLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.FAMaximumLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.FAMaximumLabel_2.setWordWrap(False)
        self.FAMaximumLabel_2.setObjectName("FAMaximumLabel_2")
        self.FAMaximumEdit_2 = QtWidgets.QLineEdit(self.FuzzingAreaFrame_2)
        self.FAMaximumEdit_2.setGeometry(QtCore.QRect(150, 200, 171, 20))
        self.FAMaximumEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.FAMaximumEdit_2.setObjectName("FAMaximumEdit_2")
        self.FAStopButton_2 = QtWidgets.QPushButton(self.FuzzingAreaFrame_2)
        self.FAStopButton_2.setGeometry(QtCore.QRect(250, 270, 71, 25))
        self.FAStopButton_2.setObjectName("FAStopButton_2")
        self.FAFuzzButton_2 = QtWidgets.QPushButton(self.FuzzingAreaFrame_2)
        self.FAFuzzButton_2.setGeometry(QtCore.QRect(170, 270, 71, 25))
        self.FAFuzzButton_2.setObjectName("FAFuzzButton_2")
        self.FilterFrame_2 = QtWidgets.QFrame(self.PCAPViewPage)
        self.FilterFrame_2.setGeometry(QtCore.QRect(10, 140, 821, 71))
        self.FilterFrame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.FilterFrame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FilterFrame_2.setObjectName("FilterFrame_2")
        self.CaptureFiltreLabel_2 = QtWidgets.QLabel(self.FilterFrame_2)
        self.CaptureFiltreLabel_2.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.CaptureFiltreLabel_2.setObjectName("CaptureFiltreLabel_2")
        self.FilterLable_2 = QtWidgets.QLabel(self.FilterFrame_2)
        self.FilterLable_2.setGeometry(QtCore.QRect(20, 40, 54, 14))
        self.FilterLable_2.setObjectName("FilterLable_2")
        self.FilterExpressionEdit_2 = QtWidgets.QLineEdit(self.FilterFrame_2)
        self.FilterExpressionEdit_2.setGeometry(QtCore.QRect(80, 40, 571, 21))
        self.FilterExpressionEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterExpressionEdit_2.setObjectName("FilterExpressionEdit_2")
        self.ApplyExpressionButton_2 = QtWidgets.QPushButton(self.FilterFrame_2)
        self.ApplyExpressionButton_2.setGeometry(QtCore.QRect(660, 40, 71, 25))
        self.ApplyExpressionButton_2.setObjectName("ApplyExpressionButton_2")
        self.ClearExpressionButton_2 = QtWidgets.QPushButton(self.FilterFrame_2)
        self.ClearExpressionButton_2.setGeometry(QtCore.QRect(740, 40, 71, 25))
        self.ClearExpressionButton_2.setObjectName("ClearExpressionButton_2")
        self.FieldAreaFrame_2 = QtWidgets.QFrame(self.PCAPViewPage)
        self.FieldAreaFrame_2.setGeometry(QtCore.QRect(10, 540, 451, 301))
        self.FieldAreaFrame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.FieldAreaFrame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FieldAreaFrame_2.setObjectName("FieldAreaFrame_2")
        self.FieldAreaLabel_2 = QtWidgets.QLabel(self.FieldAreaFrame_2)
        self.FieldAreaLabel_2.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.FieldAreaLabel_2.setObjectName("FieldAreaLabel_2")
        self.FieldAreaTable_2 = QtWidgets.QTableWidget(self.FieldAreaFrame_2)
        self.FieldAreaTable_2.setGeometry(QtCore.QRect(10, 40, 431, 211))
        self.FieldAreaTable_2.setShowGrid(False)
        self.FieldAreaTable_2.setObjectName("FieldAreaTable_2")
        self.FieldAreaTable_2.setColumnCount(4)
        self.FieldAreaTable_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.FieldAreaTable_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.FieldAreaTable_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.FieldAreaTable_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.FieldAreaTable_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.FieldAreaTable_2.setHorizontalHeaderItem(3, item)
        self.FieldAreaTable_2.horizontalHeader().setStretchLastSection(True)
        self.FieldAreaTable_2.verticalHeader().setVisible(False)
        self.FieldAreaTable_2.verticalHeader().setStretchLastSection(False)
        self.FASaveButton_2 = QtWidgets.QPushButton(self.FieldAreaFrame_2)
        self.FASaveButton_2.setGeometry(QtCore.QRect(170, 270, 111, 25))
        self.FASaveButton_2.setObjectName("FASaveButton_2")
        self.FAForwardButton_2 = QtWidgets.QPushButton(self.FieldAreaFrame_2)
        self.FAForwardButton_2.setGeometry(QtCore.QRect(290, 270, 71, 25))
        self.FAForwardButton_2.setObjectName("FAForwardButton_2")
        self.FADropButton_2 = QtWidgets.QPushButton(self.FieldAreaFrame_2)
        self.FADropButton_2.setGeometry(QtCore.QRect(370, 270, 71, 25))
        self.FADropButton_2.setObjectName("FADropButton_2")
        self.FAAddButton_2 = QtWidgets.QToolButton(self.PCAPViewPage)
        self.FAAddButton_2.setGeometry(QtCore.QRect(470, 640, 27, 20))
        self.FAAddButton_2.setArrowType(QtCore.Qt.RightArrow)
        self.FAAddButton_2.setObjectName("FAAddButton_2")
        self.PacketAreaFrame_2 = QtWidgets.QFrame(self.PCAPViewPage)
        self.PacketAreaFrame_2.setGeometry(QtCore.QRect(10, 220, 821, 311))
        self.PacketAreaFrame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.PacketAreaFrame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.PacketAreaFrame_2.setObjectName("PacketAreaFrame_2")
        self.PacketAreaLabel_2 = QtWidgets.QLabel(self.PacketAreaFrame_2)
        self.PacketAreaLabel_2.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.PacketAreaLabel_2.setObjectName("PacketAreaLabel_2")
        self.PacketAreaTabs_2 = QtWidgets.QTabWidget(self.PacketAreaFrame_2)
        self.PacketAreaTabs_2.setGeometry(QtCore.QRect(10, 40, 721, 261))
        self.PacketAreaTabs_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.PacketAreaTabs_2.setObjectName("PacketAreaTabs_2")
        self.DissectedTab_2 = QtWidgets.QWidget()
        self.DissectedTab_2.setObjectName("DissectedTab_2")
        self.PacketAreaTabs_2.addTab(self.DissectedTab_2, "")
        self.BinaryTab_2 = QtWidgets.QWidget()
        self.BinaryTab_2.setObjectName("BinaryTab_2")
        self.PacketAreaTabs_2.addTab(self.BinaryTab_2, "")
        self.HexTab_2 = QtWidgets.QWidget()
        self.HexTab_2.setObjectName("HexTab_2")
        self.PacketAreaTabs_2.addTab(self.HexTab_2, "")
        self.PacketAreaClearButton_2 = QtWidgets.QPushButton(self.PacketAreaFrame_2)
        self.PacketAreaClearButton_2.setGeometry(QtCore.QRect(740, 270, 71, 25))
        self.PacketAreaClearButton_2.setObjectName("PacketAreaClearButton_2")
        self.FASubstractButton_2 = QtWidgets.QToolButton(self.PCAPViewPage)
        self.FASubstractButton_2.setGeometry(QtCore.QRect(470, 690, 27, 20))
        self.FASubstractButton_2.setArrowType(QtCore.Qt.LeftArrow)
        self.FASubstractButton_2.setObjectName("FASubstractButton_2")
        self.HookCollectionLabel_2 = QtWidgets.QLabel(self.PCAPViewPage)
        self.HookCollectionLabel_2.setGeometry(QtCore.QRect(0, 0, 841, 51))
        self.HookCollectionLabel_2.setStyleSheet("border-style: solid solid none solid;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgb(111, 168, 220), stop:1 rgb(159, 197, 232));")
        self.HookCollectionLabel_2.setObjectName("HookCollectionLabel_2")
        self.FilterFrame_3 = QtWidgets.QFrame(self.PCAPViewPage)
        self.FilterFrame_3.setGeometry(QtCore.QRect(10, 60, 821, 71))
        self.FilterFrame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.FilterFrame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FilterFrame_3.setObjectName("FilterFrame_3")
        self.CaptureFiltreLabel_4 = QtWidgets.QLabel(self.FilterFrame_3)
        self.CaptureFiltreLabel_4.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.CaptureFiltreLabel_4.setObjectName("CaptureFiltreLabel_4")
        self.FilterLable_4 = QtWidgets.QLabel(self.FilterFrame_3)
        self.FilterLable_4.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.FilterLable_4.setObjectName("FilterLable_4")
        self.FilterExpressionEdit_4 = QtWidgets.QLineEdit(self.FilterFrame_3)
        self.FilterExpressionEdit_4.setGeometry(QtCore.QRect(80, 40, 571, 21))
        self.FilterExpressionEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterExpressionEdit_4.setObjectName("FilterExpressionEdit_4")
        self.ApplyExpressionButton_4 = QtWidgets.QPushButton(self.FilterFrame_3)
        self.ApplyExpressionButton_4.setGeometry(QtCore.QRect(660, 40, 71, 25))
        self.ApplyExpressionButton_4.setObjectName("ApplyExpressionButton_4")
        self.ClearExpressionButton_4 = QtWidgets.QPushButton(self.FilterFrame_3)
        self.ClearExpressionButton_4.setGeometry(QtCore.QRect(740, 40, 71, 25))
        self.ClearExpressionButton_4.setObjectName("ClearExpressionButton_4")
        self.ContentViewWidget.addWidget(self.PCAPViewPage)
        self.OptionViewFrame = QtWidgets.QFrame(self.MainWidget)
        self.OptionViewFrame.setGeometry(QtCore.QRect(10, 10, 251, 851))
        self.OptionViewFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.OptionViewFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OptionViewFrame.setObjectName("OptionViewFrame")
        self.OptionViewLable = QtWidgets.QLabel(self.OptionViewFrame)
        self.OptionViewLable.setGeometry(QtCore.QRect(0, 0, 251, 51))
        self.OptionViewLable.setStyleSheet("border-style: solid solid none solid;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgb(111, 168, 220), stop:1 rgb(159, 197, 232));")
        self.OptionViewLable.setObjectName("OptionViewLable")
        self.OVHookCollectionButton = QtWidgets.QPushButton(self.OptionViewFrame)
        self.OVHookCollectionButton.setGeometry(QtCore.QRect(10, 120, 231, 51))
        self.OVHookCollectionButton.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.OVHookCollectionButton.setCheckable(True)
        self.OVHookCollectionButton.setChecked(False)
        self.OVHookCollectionButton.setFlat(True)
        self.OVHookCollectionButton.setObjectName("OVHookCollectionButton")
        self.OVLivePacketButton = QtWidgets.QPushButton(self.OptionViewFrame)
        self.OVLivePacketButton.setGeometry(QtCore.QRect(10, 180, 231, 51))
        self.OVLivePacketButton.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.OVLivePacketButton.setCheckable(True)
        self.OVLivePacketButton.setChecked(False)
        self.OVLivePacketButton.setAutoDefault(False)
        self.OVLivePacketButton.setDefault(False)
        self.OVLivePacketButton.setFlat(True)
        self.OVLivePacketButton.setObjectName("OVLivePacketButton")
        self.OVPacketPCAPButton = QtWidgets.QPushButton(self.OptionViewFrame)
        self.OVPacketPCAPButton.setGeometry(QtCore.QRect(10, 240, 231, 51))
        self.OVPacketPCAPButton.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.OVPacketPCAPButton.setCheckable(True)
        self.OVPacketPCAPButton.setChecked(False)
        self.OVPacketPCAPButton.setFlat(True)
        self.OVPacketPCAPButton.setObjectName("OVPacketPCAPButton")
        self.OVHookButton = QtWidgets.QPushButton(self.OptionViewFrame)
        self.OVHookButton.setGeometry(QtCore.QRect(10, 60, 231, 51))
        self.OVHookButton.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"")
        self.OVHookButton.setCheckable(True)
        self.OVHookButton.setChecked(False)
        self.OVHookButton.setFlat(True)
        self.OVHookButton.setObjectName("OVHookButton")
        MainWindow.setCentralWidget(self.MainWidget)


        self.retranslateUi(MainWindow)
        self.ContentViewWidget.setCurrentIndex(3)
        self.PacketAreaTabs.setCurrentIndex(0)
        self.PacketAreaTabs_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
 

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Network Trafic Proxy System"))
        self.HookCollectionLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Hook Collection View</span></p></body></html>"))
        self.HCVAddHookButton.setText(_translate("MainWindow", "+Hook Collection"))
        self.HCVSearchBox.setPlaceholderText(_translate("MainWindow", "Name of Hook Collection"))
        self.HCVDeleteHookButton.setText(_translate("MainWindow", "Delete"))
        self.HCVEditHookButton.setText(_translate("MainWindow", "Edit"))
        self.HCVSearchLable.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; font-weight:600;\">Search</span></p></body></html>"))
        self.HookCollectionPropertiesLable.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Hook Collection Properties</span></p></body></html>"))
        self.HookViewLable.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Hook View</span></p></body></html>"))
        self.HVAddHookButton.setText(_translate("MainWindow", "+Hook"))
        self.HVEditHookButton.setText(_translate("MainWindow", "Edit"))
        self.HVDeleteHookButton.setText(_translate("MainWindow", "Delete"))
        self.HVSearchLable.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; font-weight:600;\">Search</span></p></body></html>"))
        self.HVSearchBox.setPlaceholderText(_translate("MainWindow", "Name of Hook"))
        self.HookPropertiesLable.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Hook Properties</span></p></body></html>"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hook"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Association to Hook\n"
"Collection"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Hook 1"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Description of Hook_name1"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "Hook 2"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "Descritption of Hook_name2"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "0"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.LivePacketViewLable.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Live Packet View</span></p></body></html>"))
        self.ProxyBox.setItemText(0, _translate("MainWindow", "Disabled"))
        self.ProxyBox.setItemText(1, _translate("MainWindow", "Enabled"))
        self.ProxyBehaviorLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Proxy Behavior</span></p></body></html>"))
        self.IntercepBehaviorLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Interception Behavior</span></p></body></html>"))
        self.InterceptBox.setItemText(0, _translate("MainWindow", "Disabled"))
        self.InterceptBox.setItemText(1, _translate("MainWindow", "Enabled"))
        self.QueueSizeLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Queue Size</span></p></body></html>"))
        self.QueueSizeEdit.setPlaceholderText(_translate("MainWindow", "Queue Size"))
        self.CaptureFiltreLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Capture Filter</span></p></body></html>"))
        self.FilterLable.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Filter</span></p></body></html>"))
        self.FilterExpressionEdit.setPlaceholderText(_translate("MainWindow", "Filter Expression"))
        self.ApplyExpressionButton.setText(_translate("MainWindow", "Apply"))
        self.ClearExpressionButton.setText(_translate("MainWindow", "Clear"))
        self.PacketAreaLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Packet Area</span></p></body></html>"))
        self.PacketAreaTabs.setTabText(self.PacketAreaTabs.indexOf(self.DissectedTab), _translate("MainWindow", "Dissected"))
        self.PacketAreaTabs.setTabText(self.PacketAreaTabs.indexOf(self.BinaryTab), _translate("MainWindow", "Binary"))
        self.PacketAreaTabs.setTabText(self.PacketAreaTabs.indexOf(self.HexTab), _translate("MainWindow", "HEX"))
        self.PacketAreaClearButton.setText(_translate("MainWindow", "Clear"))
        self.FieldAreaLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Field Area</span></p></body></html>"))
        item = self.FieldAreaTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Field Name"))
        item = self.FieldAreaTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        item = self.FieldAreaTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mask"))
        item = self.FieldAreaTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Display Format"))
        self.FASaveButton.setText(_translate("MainWindow", "Save Modification"))
        self.FAForwardButton.setText(_translate("MainWindow", "Forward"))
        self.FADropButton.setText(_translate("MainWindow", "Drop"))
        self.FuzzingAreaLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Fuzzing Area</span></p></body></html>"))
        self.FAPacketNameLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Selected Packet Name</span></p></body></html>"))
        self.FAPacketNameEdit.setPlaceholderText(_translate("MainWindow", "Selected Packet Name"))
        self.FAFieldNameLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Selected Field Name</span></p></body></html>"))
        self.FAFieldNameEdit.setPlaceholderText(_translate("MainWindow", "Selected Field Name"))
        self.FAReturnTypeLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Expected Retrun Type</span></p></body></html>"))
        self.FAReturnTypeEdit.setPlaceholderText(_translate("MainWindow", "Return Type"))
        self.FAMinimumLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Minimum</span></p></body></html>"))
        self.FAMinimumEdit.setPlaceholderText(_translate("MainWindow", "Minimum"))
        self.FAMaximumLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Maximum</span></p></body></html>"))
        self.FAMaximumEdit.setPlaceholderText(_translate("MainWindow", "Maximum"))
        self.FAStopButton.setText(_translate("MainWindow", "Stop"))
        self.FAFuzzButton.setText(_translate("MainWindow", "Fuzz"))
        self.FAAddButton.setText(_translate("MainWindow", "..."))
        self.FASubstractButton.setText(_translate("MainWindow", "..."))
        self.FuzzingAreaLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Fuzzing Area</span></p></body></html>"))
        self.FAPacketNameLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Selected Packet Name</span></p></body></html>"))
        self.FAPacketNameEdit_2.setPlaceholderText(_translate("MainWindow", "Selected Packet Name"))
        self.FAFieldNameLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Selected Field Name</span></p></body></html>"))
        self.FAFieldNameEdit_2.setPlaceholderText(_translate("MainWindow", "Selected Field Name"))
        self.FAReturnTypeLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Expected Retrun Type</span></p></body></html>"))
        self.FAReturnTypeEdit_2.setPlaceholderText(_translate("MainWindow", "Return Type"))
        self.FAMinimumLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Minimum</span></p></body></html>"))
        self.FAMinimumEdit_2.setPlaceholderText(_translate("MainWindow", "Minimum"))
        self.FAMaximumLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Maximum</span></p></body></html>"))
        self.FAMaximumEdit_2.setPlaceholderText(_translate("MainWindow", "Maximum"))
        self.FAStopButton_2.setText(_translate("MainWindow", "Stop"))
        self.FAFuzzButton_2.setText(_translate("MainWindow", "Fuzz"))
        self.CaptureFiltreLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Capture Filter</span></p></body></html>"))
        self.FilterLable_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Filter</span></p></body></html>"))
        self.FilterExpressionEdit_2.setPlaceholderText(_translate("MainWindow", "Filter Expression"))
        self.ApplyExpressionButton_2.setText(_translate("MainWindow", "Apply"))
        self.ClearExpressionButton_2.setText(_translate("MainWindow", "Clear"))
        self.FieldAreaLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Field Area</span></p></body></html>"))
        item = self.FieldAreaTable_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Field Name"))
        item = self.FieldAreaTable_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        item = self.FieldAreaTable_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mask"))
        item = self.FieldAreaTable_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Display Format"))
        self.FASaveButton_2.setText(_translate("MainWindow", "Save Modification"))
        self.FAForwardButton_2.setText(_translate("MainWindow", "Forward"))
        self.FADropButton_2.setText(_translate("MainWindow", "Drop"))
        self.FAAddButton_2.setText(_translate("MainWindow", "..."))
        self.PacketAreaLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Packet Area</span></p></body></html>"))
        self.PacketAreaTabs_2.setTabText(self.PacketAreaTabs_2.indexOf(self.DissectedTab_2), _translate("MainWindow", "Dissected"))
        self.PacketAreaTabs_2.setTabText(self.PacketAreaTabs_2.indexOf(self.BinaryTab_2), _translate("MainWindow", "Binary"))
        self.PacketAreaTabs_2.setTabText(self.PacketAreaTabs_2.indexOf(self.HexTab_2), _translate("MainWindow", "HEX"))
        self.PacketAreaClearButton_2.setText(_translate("MainWindow", "Clear"))
        self.FASubstractButton_2.setText(_translate("MainWindow", "..."))
        self.HookCollectionLabel_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Packet from PCAP View</span></p></body></html>"))
        self.CaptureFiltreLabel_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">PCAP File</span></p><p><br/></p></body></html>"))
        self.FilterLable_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">PCAP File</span></p></body></html>"))
        self.FilterExpressionEdit_4.setPlaceholderText(_translate("MainWindow", "PCAP File Path"))
        self.ApplyExpressionButton_4.setText(_translate("MainWindow", "Open"))
        self.ClearExpressionButton_4.setText(_translate("MainWindow", "Cancel"))
        self.OptionViewLable.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Option View</span></p></body></html>"))
        self.OVHookCollectionButton.setText(_translate("MainWindow", "Hook Collection"))
        self.OVLivePacketButton.setText(_translate("MainWindow", "Live Packet"))
        self.OVPacketPCAPButton.setText(_translate("MainWindow", "Packet from PCAP"))
        self.OVHookButton.setText(_translate("MainWindow", "Hook"))


class ControlMainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(ControlMainWindow, self).__init__(parent)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.ui.OVHookCollectionButton.clicked.connect(lambda : self.ui.ContentViewWidget.setCurrentIndex(0)) 
        self.ui.OVHookButton.clicked.connect(lambda : self.ui.ContentViewWidget.setCurrentIndex(1))
        self.ui.OVLivePacketButton.clicked.connect(lambda : self.ui.ContentViewWidget.setCurrentIndex(2))
        self.ui.OVPacketPCAPButton.clicked.connect(lambda : self.ui.ContentViewWidget.setCurrentIndex(3))

        self.ui.HCVEditHookButton.clicked.connect(lambda : self.showEditHook())
        self.ui.HVEditHookButton.clicked.connect(lambda: self.showEditHookCollection())

    def showEditHook(self):
        dialog = QtWidgets.QDialog()
        ui = EditHook.Ui_CreatEditHookOverlay()
        ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()


    def showEditHookCollection(self):
        dialog = QtWidgets.QDialog()
        ui = EditHookCollectionOverlay.UI_Dialog()
        ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow = ControlMainWindow()
    MainWindow.show()
    sys.exit(app.exec_())
